import { Info } from 'lucide-react'

interface TaxDisclaimerProps {
  /** Use sticky positioning at bottom of page */
  sticky?: boolean
  /** Additional className */
  className?: string
}

/**
 * TaxDisclaimer - TASA 2009 compliant legal disclaimer
 *
 * MUST appear on every page showing tax recommendations or dollar estimates.
 * Required under Tax Agent Services Act 2009 s 50-5.
 */
export function TaxDisclaimer({ sticky = false, className = '' }: TaxDisclaimerProps) {
  const baseClass = sticky ? 'sticky-disclaimer mt-8' : 'mt-8 p-4 bg-white/[0.02] border border-white/5'

  return (
    <div
      className={`${baseClass} ${className}`.trim()}
      style={{ borderRadius: 'var(--radius-sm)' }}
      role="contentinfo"
      aria-label="Legal disclaimer"
    >
      <div className="flex items-start gap-3">
        <Info className="w-4 h-4 flex-shrink-0 mt-0.5" style={{ color: 'var(--text-muted)' }} />
        <p className="text-[10px] leading-relaxed" style={{ color: 'var(--text-muted)' }}>
          <strong style={{ color: 'var(--text-tertiary)' }}>DISCLAIMER:</strong>{' '}
          This analysis is generated by automated software and does not constitute tax, financial,
          or legal advice. It is provided for informational purposes only. All findings and
          recommendations should be reviewed by a registered tax agent or qualified tax professional
          before any action is taken. This software is not registered with the Tax Practitioners Board
          and does not provide tax agent services within the meaning of the Tax Agent Services Act 2009 (TASA).
          All dollar amounts shown are estimates based on available data and may not reflect your final tax position.
        </p>
      </div>
    </div>
  )
}
