#!/usr/bin/env tsx

/**
 * Senior PM: Generate Daily Report
 *
 * Generate a comprehensive daily progress report showing:
 * - Active projects and their status
 * - Specialist workload
 * - Blockers requiring attention
 * - Completed projects
 * - Quality gate progress
 *
 * Usage:
 *   npm run senior-pm:daily-report
 *   npm run senior-pm:daily-report -- --format markdown
 *   npm run senior-pm:daily-report -- --output report.md
 */

import { writeFile } from 'fs/promises';
import { createLinearOrchestrator } from '@/lib/linear/orchestrator';
import { createAgentCommunicationBus } from '@/lib/agents/communication';
import { createQualityGateEnforcer } from '@/lib/agents/quality-gates';
import { createSeniorPMOrchestrationManager } from '@/lib/senior-pm/orchestration-manager';

interface Args {
  format?: 'markdown' | 'json' | 'text';
  output?: string;
}

async function main() {
  const args = parseArgs();

  console.log('📊 Senior PM: Daily Progress Report\n');
  console.log(`Date: ${new Date().toLocaleDateString()}\n`);

  // Initialize components
  const linearOrchestrator = createLinearOrchestrator();
  const commBus = createAgentCommunicationBus(linearOrchestrator);
  const qualityGates = createQualityGateEnforcer(linearOrchestrator);
  const seniorPM = createSeniorPMOrchestrationManager(
    linearOrchestrator,
    commBus,
    qualityGates
  );

  try {
    // Generate report
    const report = await seniorPM.generateDailyReport();

    // Get additional metrics from Linear
    const linearReport = await linearOrchestrator.generateDailyReport();

    // Combine reports
    const combinedReport = generateCombinedReport(report, linearReport, args.format || 'markdown');

    // Output
    if (args.output) {
      await writeFile(args.output, combinedReport, 'utf-8');
      console.log(`✅ Report saved to: ${args.output}\n`);
    } else {
      console.log(combinedReport);
    }

    return { success: true, report: combinedReport };
  } catch (error) {
    console.error('❌ Error generating report:', error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

function generateCombinedReport(
  pmReport: string,
  linearReport: {
    date: string;
    specialistCounts: Record<string, number>;
    completedToday: string[];
    blocked: Array<{ title: string; url: string }>;
    totalActive: number;
  },
  format: 'markdown' | 'json' | 'text'
): string {
  if (format === 'json') {
    return JSON.stringify(
      {
        date: linearReport.date,
        pmReport,
        linearMetrics: linearReport,
      },
      null,
      2
    );
  }

  if (format === 'text') {
    let text = `SENIOR PM DAILY REPORT - ${new Date().toLocaleDateString()}\n\n`;
    text += pmReport.replace(/^#/gm, '').replace(/\*\*/g, '');
    return text;
  }

  // Markdown (default)
  let markdown = pmReport;
  markdown += `\n---\n\n## Linear Metrics\n\n`;
  markdown += `### Specialist Workload\n\n`;

  const specialists = linearReport.specialistCounts;
  if (Object.keys(specialists).length > 0) {
    markdown += `| Specialist | Active Tasks |\n`;
    markdown += `|------------|-------------|\n`;
    for (const [specialist, count] of Object.entries(specialists)) {
      markdown += `| ${specialist} | ${count} |\n`;
    }
  } else {
    markdown += `*No active specialist tasks*\n`;
  }

  markdown += `\n### Overall Status\n\n`;
  markdown += `- **Total Active Issues**: ${linearReport.totalActive}\n`;
  markdown += `- **Completed Today**: ${linearReport.completedToday.length}\n`;
  markdown += `- **Currently Blocked**: ${linearReport.blocked.length}\n\n`;

  if (linearReport.blocked.length > 0) {
    markdown += `### Blocked Issues (Urgent Attention Required)\n\n`;
    for (const blocked of linearReport.blocked) {
      markdown += `- [${blocked.title}](${blocked.url})\n`;
    }
    markdown += `\n`;
  }

  markdown += `---\n\n`;
  markdown += `*Report Generated*: ${new Date().toISOString()}\n`;
  markdown += `*Generated by*: Senior PM Daily Report System\n`;

  return markdown;
}

function parseArgs(): Args {
  const args = process.argv.slice(2);

  let format: Args['format'] = 'markdown';
  let output: string | undefined;

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    const nextArg = args[i + 1];

    switch (arg) {
      case '--format':
      case '-f':
        if (['markdown', 'json', 'text'].includes(nextArg)) {
          format = nextArg as Args['format'];
        }
        i++;
        break;
      case '--output':
      case '-o':
        output = nextArg;
        i++;
        break;
      case '--help':
      case '-h':
        printUsage();
        process.exit(0);
    }
  }

  return { format, output };
}

function printUsage() {
  console.log(`
📊 Senior PM: Generate Daily Report

Generate a comprehensive daily progress report for all orchestrated projects.

USAGE:
  npm run senior-pm:daily-report [options]

OPTIONS:
  --format, -f <type>     Output format: markdown, json, text (default: markdown)
  --output, -o <file>     Save to file instead of stdout

EXAMPLES:
  # Display report in terminal
  npm run senior-pm:daily-report

  # Save as markdown file
  npm run senior-pm:daily-report -- --output daily-report.md

  # Output as JSON
  npm run senior-pm:daily-report -- --format json

REPORT INCLUDES:
  - Active projects and progress
  - Specialist task counts (A/B/C/D)
  - Quality gates passed
  - Blockers requiring attention
  - Completed projects
  - Linear metrics

SCHEDULING:
  You can schedule this to run daily via cron:

  # Every day at 9 AM
  0 9 * * * cd /path/to/project && npm run senior-pm:daily-report --output reports/daily-\$(date +\%Y\%m\%d).md
  `);
}

// Run if called directly
if (require.main === module) {
  main().catch((error) => {
    console.error('Fatal error:', error);
    process.exit(1);
  });
}

export { main as generateDailyReport };
