/**
 * Accountant Application Page
 *
 * Public page for accountants to apply for wholesale pricing
 */

import ApplicationForm from '@/components/accountant/ApplicationForm';

export const metadata = {
  title: 'Apply for Accountant Pricing | Australian Tax Optimizer',
  description:
    'Apply for verified accountant status and receive wholesale pricing on all tax analysis reports.',
};

export default function AccountantApplyPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      {/* Header */}
      <div className="max-w-4xl mx-auto mb-12 text-center">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">
          Apply for Accountant Pricing
        </h1>
        <p className="text-xl text-gray-600 max-w-2xl mx-auto">
          Join our network of verified tax professionals and receive exclusive wholesale pricing
          on all reports.
        </p>
      </div>

      {/* Benefits Section */}
      <div className="max-w-4xl mx-auto mb-12 grid md:grid-cols-3 gap-6">
        <div className="bg-white p-6 rounded-lg shadow-md">
          <div className="text-3xl mb-3">💰</div>
          <h3 className="font-semibold text-lg mb-2">Wholesale Pricing</h3>
          <p className="text-gray-600 text-sm">
            $495 per report (50% off standard pricing)
          </p>
        </div>

        <div className="bg-white p-6 rounded-lg shadow-md">
          <div className="text-3xl mb-3">⚡</div>
          <h3 className="font-semibold text-lg mb-2">Instant Access</h3>
          <p className="text-gray-600 text-sm">
            Once approved, immediate access to all platform features
          </p>
        </div>

        <div className="bg-white p-6 rounded-lg shadow-md">
          <div className="text-3xl mb-3">🔒</div>
          <h3 className="font-semibold text-lg mb-2">Lifetime Benefit</h3>
          <p className="text-gray-600 text-sm">
            Maintain wholesale pricing as long as you remain active
          </p>
        </div>
      </div>

      {/* Application Form */}
      <div className="bg-white rounded-lg shadow-lg p-8">
        <ApplicationForm />
      </div>

      {/* FAQ Section */}
      <div className="max-w-4xl mx-auto mt-16">
        <h2 className="text-2xl font-bold mb-6 text-center">Frequently Asked Questions</h2>

        <div className="space-y-6">
          <div className="bg-white p-6 rounded-lg shadow">
            <h3 className="font-semibold mb-2">Who is eligible for accountant pricing?</h3>
            <p className="text-gray-600 text-sm">
              Registered tax professionals including CPAs, CAs, Registered Tax Agents, BAS Agents,
              and other qualified accountants with valid credentials.
            </p>
          </div>

          <div className="bg-white p-6 rounded-lg shadow">
            <h3 className="font-semibold mb-2">How long does the approval process take?</h3>
            <p className="text-gray-600 text-sm">
              Most applications are reviewed within 24-48 hours. We verify your credentials with
              the relevant issuing body to ensure quality control.
            </p>
          </div>

          <div className="bg-white p-6 rounded-lg shadow">
            <h3 className="font-semibold mb-2">What happens after I'm approved?</h3>
            <p className="text-gray-600 text-sm">
              You'll receive a welcome email with a magic link to set up your account. You'll have
              immediate access to wholesale pricing ($495 vs $995) and can start generating reports
              right away.
            </p>
          </div>

          <div className="bg-white p-6 rounded-lg shadow">
            <h3 className="font-semibold mb-2">Can I invite team members?</h3>
            <p className="text-gray-600 text-sm">
              Yes! Once approved, you can create an organization and invite team members to
              collaborate on client reports. Wholesale pricing applies to all reports generated by
              your organization.
            </p>
          </div>

          <div className="bg-white p-6 rounded-lg shadow">
            <h3 className="font-semibold mb-2">Is there a minimum commitment?</h3>
            <p className="text-gray-600 text-sm">
              No. There are no ongoing fees, minimums, or commitments. You only pay when you
              generate a report ($495 per report).
            </p>
          </div>
        </div>
      </div>

      {/* Contact Section */}
      <div className="max-w-4xl mx-auto mt-12 text-center">
        <p className="text-gray-600 mb-4">Have questions about the application process?</p>
        <a
          href="mailto:accountants@ato.example.com"
          className="inline-block px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
        >
          Contact Our Team
        </a>
      </div>
    </div>
  );
}
